list_examples.v
list_predicates.v
list_tactics.v
ex01_head.v
ex02_tail.v
ex03_add.v
ex04_swap.v
ex05_deallocate.v
ex06_length_recursive.v
ex07_length_iterative.v
ex08_sum_recursive.v
ex09_sum_iterative.v
ex10_reverse.v
ex11_append.v
ex12_copy.v
ex13_delete.v
ho.v
