FILES:=equate_map_reflection.v map_disjointness.v maps.v pattern_simpl.v patterns.v pattern_tactics.v proof.v zipper_patterns.v

include coq_makefile.mk

coq_makefile.mk : Makefile
	coq_makefile $(FILES) > $@
